# Generated by Django 6.1 on 2026-08-28 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_socialaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('creator', 'Content Creator'), ('marketing', 'Marketing Team'), ('business', 'Business User'), ('administrator', 'Administrator')], default='creator', max_length=20)),
                ('status', models.CharField(default='invited', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('carousel', 'Carousel'), ('story', 'Story'), ('reel', 'Reel')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='queue_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='recurrence',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('user', 'platform', 'account_id'), name='unique_social_account'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammember',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('owner', 'member'), name='unique_team_member'),
        ),
    ]
