# Generated by Django 6.1 on 2026-09-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_milestone2_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledpost',
            options={'ordering': ['-scheduled_time']},
        ),
        migrations.RenameIndex(
            model_name='publishingqueue',
            new_name='scheduler_p_status_8a003c_idx',
            old_name='scheduler_p_status_idx',
        ),
    ]
